# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')])),
            ],
        ),
        migrations.CreateModel(
            name='Enterpriseprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('descriptor', models.CharField(max_length=255)),
                ('profileImage', models.ImageField(blank=True, upload_to=b'')),
                ('bannerImage', models.ImageField(blank=True, upload_to=b'')),
                ('businessName', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('legalId', models.CharField(max_length=11, unique=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('web', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('us', models.CharField(max_length=600)),
                ('offer', models.CharField(max_length=600)),
                ('searchKeywords', models.CharField(blank=True, max_length=180)),
                ('relationship', models.ManyToManyField(related_name='related_to', through='enterpriseprofiles.Client', to='enterpriseprofiles.Enterpriseprofile')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_enterprise', to='enterpriseprofiles.Enterpriseprofile'),
        ),
        migrations.AddField(
            model_name='client',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_enterprise', to='enterpriseprofiles.Enterpriseprofile'),
        ),
    ]
