# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseprofile',
            name='relationship',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='enterpriseprofiles.Client', to='enterpriseprofiles.Enterpriseprofile'),
        ),
    ]
