# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseprofiles', '0004_auto_20160218_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseprofile',
            name='facebookURL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='enterpriseprofile',
            name='instagramURL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='enterpriseprofile',
            name='twitterURL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='enterpriseprofile',
            name='youtubeURL',
            field=models.URLField(blank=True),
        ),
    ]
